config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :to_dos, :only => [:new, :create, :destroy]
  resources :to_do_lists, :only => [:show, :create, :destroy]
  resources :campaigns, :only => [:index, :new, :show, :create, :destroy]
  resources :comments, :only => [:index, :new, :create, :destroy]
  devise_for :installs
  devise_for :users, :path_prefix => 'my', controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations"
  }
  resources :users
  root to: 'pages#home'
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'
end

app/views/pages/dashboard.html.erb
<h1>Dashboard</h1>
<h3>Welcome <%=current_user.username.capitalize%></h3>

<% if @user.expert %>
  <h3>Your profile</h3>

  <ul style="list-style-type:none">
    <li>You are an expert</li>
    <li>Your profession: <%=current_user.profession%></li>
    <li>Your service: <%=current_user.service%></li>
    <li>Your status: <%=current_user.status%></li>

  </ul>

  <%= link_to "Create a New Campaign", new_campaign_path, class: 'button' %>
  <%#= link_to "Set novice to expert", new_campaign_path, class: 'button' %>

  <h3>Your campaigns</h3>
  <ul>
    <% current_user.campaigns.each do |campaign|%>

      <li><%= link_to campaign.title, campaign %> |<%=campaign.duration%> min
        <% unless campaign.tags == [] %>
          |
          <% campaign.tags.each do |tag|%>
            <%= tag %>
          <% end %>
        <% end %>
      </li>
    <% end %>
  </ul>
  <%= link_to "See all Current Campaigns", campaigns_path, class: 'button' %>


<% else current_user.expert %>
<p>You are a novice. Your status: <%=current_user.status%></p>
  <%= link_to "Check Current Campaigns", campaigns_path, class: 'button' %>



<% end %>

app/views/pages/home.html.erb
<h1>Campaign Manager</h1>

<p>Create and Manage your Campaigns and ToDo Lists</p>

<% if user_signed_in? %>
  <%= link_to "Go to your Dashboard", dashboard_path, class: "navbar-wagon-item" %>
<% else %>
  <%= link_to "Sign-up", new_user_registration_path %> or
  <%= link_to "Log-in", new_user_session_path %>
<% end %>