config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :to_dos, :only => [:new, :create, :destroy]
  resources :to_do_lists, :only => [:show, :create, :destroy]
  resources :campaigns, :only => [:index, :new, :show, :create, :destroy]
  resources :comments, :only => [:index, :new, :create, :destroy]
  devise_for :installs
  devise_for :users, :path_prefix => 'my', controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations"
  }
  resources :users
  root to: 'pages#home'
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  # A campaign is composed of title, tags and estimated duration [in min].
  belongs_to :user
  has_many :to_do_lists
  has_many :comments

  validates :title, presence: true, length: { in: 2..50 }
  validates :duration, presence: true, numericality: { only_integer: true }

end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
    before_action :set_campaign, only: [:show, :destroy]

  def index
    @campaigns = Campaign.all
    authorize @campaigns
  end

  def new
    @campaign = Campaign.new
    authorize @campaign
  end

  def show
    authorize @campaign
    @to_do_lists = ToDoList.where(campaign_id: @campaign.id)
    @comment = Comment.new
    authorize @comment
    @comments = Comment.where(campaign_id: @campaign.id)
    @to_do_list = ToDoList.new
    authorize @to_do_list
  end

  def create
    # @params.tags = @params.tags.split(", ")
    #@campaign = Campaign.new(params[:campaign])
    @campaign = Campaign.new(campaign_params)
    @campaign.user = current_user
    authorize @campaign
    if @campaign.save
    # redirect_to campaign_path(@campaign)
    redirect_to dashboard_path
    else
      render "new"
    end
  end

  def destroy
    @campaign.destroy
  end

  private

  def set_campaign
    @campaign = Campaign.find(params[:id])
  end

  def campaign_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    params.require(:campaign).permit(:title, :tags, :duration)
  end
end

app/views/campaigns/create.html.erb
<h1>Campaigns#create</h1>
<p>Find me in app/views/campaigns/create.html.erb</p>

app/views/campaigns/destroy.html.erb
<h1>Campaigns#destroy</h1>
<p>Find me in app/views/campaigns/destroy.html.erb</p>

app/views/campaigns/index.html.erb
<h1>Current Campaigns</h1>
<%# Find me in app/views/campaigns/index.html.erb %>

<ul style="list-style-type:none">
  <% Campaign.all.each do |campaign|%>
    <li><%= link_to campaign.title, campaign %> |
      <%=campaign.duration%> min
      <%=" | #{campaign.tags}" unless campaign.tags == [] %> </li>
  <% end %>

</ul>


<% if current_user.expert %>
  <%= link_to "Create a new campaign", new_campaign_path, class: 'button' %>
<% end %>

app/views/campaigns/new.html.erb
<h1>Campaigns#new</h1>
<p>Find me in app/views/campaigns/new.html.erb</p>

<%= simple_form_for @campaign do |f| %>
  <%= f.input :title %>
  <%= f.input :duration, as: :integer, hint: "in minutes" %>
  <%= f.input :tags, multiple: true %>
  <%= f.button :submit %>
<% end %>

app/views/campaigns/show.html.erb
<h1><%= @campaign.title.capitalize %></h1>

Estimated Duration: <%=@campaign.duration%> min
<%=" | #{@campaign.tags}" unless @campaign.tags == [] %>

<h3>Comments to this Campaign</h3>
<ul style="list-style-type:none">
  <% @comments.each do |comment| %>
    <li> <b><%= comment.title %> </b> written by <%= comment.user.username %></li>
  <% end %>
</ul>

<%= simple_form_for @comment do |f| %>
  <%= f.input :title %>
  <%#= f.hidden_field :campaign_id, :value => @campaign.id %>
  <%= hidden_field_tag 'campaign_id', @campaign.id %>
  <%= f.button :submit %>
<% end %>

<h5><%#= link_to "Add Comment", new_comment_path(@campaign) %></h5>

<h3>To Do Lists in this Campaign</h3>
<ul style="list-style-type:none">
  <% @to_do_lists.each do |list| %>
  <li><%= link_to list.listname.capitalize, list %></li>
    <li><%#= list.listname.capitalize %></li>
  <% end %>
</ul>

<h5><%#= link_to "Add To Do List", new_to_do_list_path %></h5>

<%= simple_form_for @to_do_list do |f| %>
  <%= f.input :listname %>
  <%#= f.hidden_field :campaign_id, :value => @campaign.id %>
  <%= hidden_field_tag 'campaign_id', @campaign.id %>
  <%= f.button :submit %>
<% end %>